force-app/main/default/objects/CESS_Integration_Event__e/CESS_Integration_Event__e.object-meta.xml
<CustomObject>
    <label>CESS Integration Event</label>
    <pluralLabel>CESS Integration Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/CESS_Integration_Event__e/fields/System__c.field-meta.xml
<CustomField>
    <fullName>System__c</fullName>
    <label>System</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CESS_Integration_Event__e/fields/Times_Retried__c.field-meta.xml
<CustomField>
    <fullName>Times_Retried__c</fullName>
    <label>Times Retried</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CESS_IntegrationEventTrigger_Test.cls
/**********************************************************************************
* @author       Francisco Pérez - franciscojose.perez@salesforce.com
* @date         16/06/2020
* @group        Test
* @description  Tests for trigger CESS_IntegrationEventTrigger
* @revision
**********************************************************************************/
@isTest
private class CESS_IntegrationEventTrigger_Test {
	/**
     * @description
     */   
	@testSetup
	private static void setup() {

	} 

	/**
     * @description
     */   
	@isTest
	private static void test() {
		Test.startTest();

		EventBus.publish(new CESS_Integration_Event__e(
			System__c = 'Test',
			Data__c = '{"error": false}',
			Times_Retried__c = 1,
			Handler__c = 'CESS_IntegrationEventLogicTest'
        ));

		Test.stopTest();
	}
}