force-app/main/default/objects/IntegrationLog__c/IntegrationLog__c.object-meta.xml
<CustomObject>
    <label>Log de Integración</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log de Integración</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IntegrationLog__c/fields/data__c.field-meta.xml
<CustomField>
    <fullName>data__c</fullName>
    <label>Datos</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IntegrationLog__c/fields/system__c.field-meta.xml
<CustomField>
    <fullName>system__c</fullName>
    <label>Sistema</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/source_manualrecord__c.field-meta.xml
<CustomField>
    <fullName>source_manualrecord__c</fullName>
    <label>Origen - Registro Manual</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Complet FECISA</fullName>
            </value>
            <value>
                <fullName>Llamada Entrante</fullName>
            </value>
            <value>
                <fullName>Referencia</fullName>
            </value>
            <value>
                <fullName>Venta Presencial</fullName>
            </value>
            <value>
                <fullName>Gestión de Cartera</fullName>
            </value>
            <value>
                <fullName>Otros</fullName>
            </value>
            <value>
                <fullName>Retención CESS</fullName>
            </value>
            <value>
                <fullName>Retención SECI</fullName>
            </value>
            <value>
                <fullName>Atención al Cliente CESS</fullName>
            </value>
            <value>
                <fullName>Atención al Cliente SECI</fullName>
            </value>
            <value>
                <fullName>Transcom</fullName>
            </value>
            <value>
                <fullName>Transferencia MM</fullName>
            </value>
            <value>
                <fullName>Blecis Sevilla</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ORG_Integration_Event__e/ORG_Integration_Event__e.object-meta.xml
<CustomObject>
    <label>Integration Event</label>
    <pluralLabel>Integration Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/ORG_Integration_Event__e/fields/System__c.field-meta.xml
<CustomField>
    <fullName>System__c</fullName>
    <label>System</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ORG_Integration_Event__e/fields/Times_Retried__c.field-meta.xml
<CustomField>
    <fullName>Times_Retried__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Times Retried</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ORG_IntegrationEventLogicTest.cls
/**********************************************************************************
* @author       Giovanni Modica - gmodica@salesforce.com
* @date         06/08/2018
* @group        Test
* @description  Tests for class ORG_IntegrationEventLogic
* @revision
**********************************************************************************/
@isTest
public class ORG_IntegrationEventLogicTest implements ORG_IIntegrationHandler {
	public static String setting = '[{"s": "Test","c": "ORG_IntegrationEventLogicTest","a": true, "async": true}]';

	/**
     * @description
     */   
	@testSetup
	private static void setup() {
		insert new Lead(LastName = 'Test',source_manualrecord__c='Otros',MobilePhone='632333232');
	} 

	/**
	* @description 
	*/
	public void handleEvent(ORG_Integration_Event__e event) {
		Data data = String.isNotBlank(event.Data__c) ? (Data)JSON.deserialize(event.Data__c, Data.class) : null;

		if(data.error) throw new ORG_IntegrationEventLogic.ORG_IntegrationEventException('Test');
	}

	/**
	* @description 
	*/
	public Map<String,Object> getLogValues(ORG_Integration_Event__e event) {
		return new Map<String,Object>();
	}

	/**
     * @description
     */   
	@isTest
	private static void testSolve() {
		Lead l = [select Id from Lead];

		Test.startTest();

		new ORG_IntegrationEventLogic().solveLog(l.Id,SObjectType.Lead.name + ',' + l.Id + ',' + 'update','Test');

		Test.stopTest();
	}

	/**
     * @description
     */   
	@isTest
	private static void testHandleEvents() {
		ORG_Integration_Event__e event = new ORG_Integration_Event__e(
			System__c = 'Test',
			Data__c = '{"error": false}',
			Times_Retried__c = 0
        );

		Test.startTest();

		ORG_IntegrationEventLogic.handleEvents(new List<ORG_Integration_Event__e> { event });

		Test.stopTest();
	}

	/**
     * @description
     */   
	@isTest
	private static void testHandleEventsRetried() {
		ORG_Integration_Event__e event = new ORG_Integration_Event__e(
			System__c = 'Test',
			Data__c = '{"error": false}',
			Times_Retried__c = 1
        );

		Test.startTest();

		String errorMessage = null;
		try {
			ORG_IntegrationEventLogic.handleEvents(new List<ORG_Integration_Event__e> { event });
		}
		catch(Exception e) {
			errorMessage = e.getMessage();
		}

		Test.stopTest();

		System.assertNotEquals(null, errorMessage);
	}	

	/**
     * @description
     */   
	@isTest
	private static void testHandleEventsRetriedMax() {
		ORG_Integration_Event__e event = new ORG_Integration_Event__e(
			System__c = 'Test',
			Data__c = '{"error": false}',
			Times_Retried__c = ORG_IntegrationEventLogic.getMaxRetries() + 1,
			Handler__c = 'ORG_IntegrationEventLogicTest'
        );

		Test.startTest();

		ORG_IntegrationEventLogic.handleEvents(new List<ORG_Integration_Event__e> { event });

		Test.stopTest();
	}	

	/**
     * @description
     */   
	@isTest
	private static void testHandleEventsRetriedMaxWithError() {
		ORG_Integration_Event__e event = new ORG_Integration_Event__e(
			System__c = 'Test',
			Data__c = '{"error": true}',
			Times_Retried__c = ORG_IntegrationEventLogic.getMaxRetries() + 1
        );

		Test.startTest();

		ORG_IntegrationEventLogic.handleEvents(new List<ORG_Integration_Event__e> { event });

		Test.stopTest();

		System.assertEquals(1, [select count() from IntegrationLog__c]);
	}			

	/**
     * @description
     */   
	@isTest
	private static void testHandleEventsWithHandler() {
		ORG_Integration_Event__e event = new ORG_Integration_Event__e(
			System__c = 'Test',
			Data__c = '{"error": false}',
			Times_Retried__c = 0,
			Handler__c = 'ORG_IntegrationEventLogicTest'
        );

		Test.startTest();

		ORG_IntegrationEventLogic.handleEvents(new List<ORG_Integration_Event__e> { event });

		Test.stopTest();
	}	

	/**
     * @description
     */   
	@isTest
	private static void testHandleEventsWithError() {
		ORG_Integration_Event__e event = new ORG_Integration_Event__e(
			System__c = 'Test',
			Data__c = '{"error": true}',
			Times_Retried__c = 0
        );

		Test.startTest();

		ORG_IntegrationEventLogic.handleEvents(new List<ORG_Integration_Event__e> { event });

		Test.stopTest();
	}	

	/**
     * @description
     */   
	@isTest
	private static void testHandleEventsWithErrorSync() {
		setting = '[{"s": "Test","c": "ORG_IntegrationEventLogicTest","a": true, "async": false}]';

		ORG_Integration_Event__e event = new ORG_Integration_Event__e(
			System__c = 'Test',
			Data__c = '{"error": true}',
			Times_Retried__c = 0
        );

		Test.startTest();

		ORG_IntegrationEventLogic.handleEvents(new List<ORG_Integration_Event__e> { event });

		Test.stopTest();
	}		

	//-- INNER CLASSES
	/**
	* @description 
	*/
	public class Data {
		public Boolean error {get; set;}
	}	
}